#' Open FAFB CATMAID in browser at a given XYZ location
#'
#' @details Note that if object \code{x} contains exactly one point then CATMAID
#'   will be opened immediately at that location, whereas if there is more than
#'   1 point, the function will stop and wait for the user to make an
#'   interactive selection in a \code{rgl} window.
#'
#'   As a special case, if \code{x} is a data.frame generated by
#'   \code{catmaid_get_treenodes_detail} then URLs will be generated for every
#'   row (i.e. each treenode). See examples.
#' @param x A numeric vector or any object compatible with
#'   \code{\link[nat]{xyzmatrix}} (see details)
#' @param s A selection function of the type returned by
#'   \code{\link[rgl]{select3d}}
#' @param mirror Whether to mirror the point to the opposite side of the brain
#' @param sample The template brain space associated with the coordinates in
#'   \code{x}
#' @param open Whether to open the url in the browser or simply return it.
#'   Defaults to \code{TRUE} when R is running in interactive mode.
#' @param zoom The CATMAID zoom factor (defaults to 1)
#' @param active_skeleton_id,active_node_id Set highlighted skeleton and node in
#'   CATMAID.
#' @param ... Additional arguments to be added to URL.
#' @export
#' @importFrom utils browseURL
#' @seealso \code{\link{xform_brain}}
#' @examples
#' open_fafb(c(316, 143, 26), sample=JFRC2013, open=FALSE)
#' library(nat)
#' \dontrun{
#' open3d()
#' plot3d(kcs20)
#' # waits for used to draw a selection rectangle
#' open_fafb(kcs20, sample=FCWB)
#' # same but mirrors selected points to opposite hemisphere
#' open_fafb(kcs20, sample=FCWB, mirror=TRUE)
#' }
#' \donttest{
#' # fetch a neuron and extract the node ids for a given tag
#' n=read.neuron.catmaid(16)
#' tagged = n$tags[['TODO']]
#' tagged_details <- catmaid_get_treenodes_detail(tagged)
#' # now find FAFB URLs
#' tagged_details$url <- open_fafb(tagged_details)
#' # take a look at results
#' head(tagged_details)
#' }
#' \dontrun{
#' # copy results to clipboard e.g. to paste into a spreadsheet
#' library(clipr)
#' write_clip(tagged_details)
#' }
open_fafb<-function(x, s=rgl::select3d(), mirror=FALSE, sample=elmr::FAFB,
                    zoom=1, open=interactive(),
                    active_skeleton_id=NULL, active_node_id=NULL, ...) {
  # special case, looks like results of catmaid_get_treenodes_detail
  if(is.data.frame(x) && c("treenode_id","skid", "x", "y", "z") %in% names(x)) {
    # looks like a data frame from catmaid_get_treenodes_detail
    xyz=xyzmatrix(x)
    urls=sapply(1:nrow(x),
                function(i) open_fafb(xyz[i,],
                                      active_skeleton_id = x[i, 'skid'],
                                      active_node_id = x[i, 'treenode_id'],
                                      open = F, ...)
                )
    return(urls)
  }
  if(is.vector(x, mode='numeric') && length(x)==3 ){
    xyz=matrix(x, ncol=3)
  } else {
    xyz=xyzmatrix(x)
    if(nrow(xyz)>1){
      # calculate centroid of points inside selection
      xyz=colMeans(xyz[s(xyz),, drop=F])
      xyz=matrix(xyz, ncol=3)
    }
  }
  if(mirror)
    xyz=mirror_brain(xyz, sample)

  csample=as.character(sample)
  if(substr(csample, 1, 4)!="FAFB"){
    xyz=xform_brain(xyz, sample = sample, reference = elmr::FAFB)
    csample=as.character(elmr::FAFB)
  }
  fafb.version=substr(csample,5,nchar(csample))

  xyzi=as.integer(xyz)
  url=sprintf("https://neuropil.janelia.org/tracing/fafb/v%s/?pid=1&zp=%d&yp=%d&xp=%d&tool=tracingtool&sid0=5&s0=%f",
              fafb.version,xyzi[3], xyzi[2], xyzi[1], zoom)
  apl=pairlist(...)
  apl$active_skeleton_id=active_skeleton_id
  apl$active_node_id=active_node_id
  if(length(apl)){
    # interpret as extra params
    url=paste0(url, "&", paste(names(apl), sep="=", apl, collapse = "&"))
  }

  if(open){
    browseURL(url)
    invisible(url)
  } else {
    url
  }
}
